<?php
define('PAGINATION_PROJECT_TYPE', 10);
define('PAGINATION_PROJECT_CATEGORY', 10);
define('PAGINATION_PROJECT', 20);
define('PAGINATION_PROJECT_PRODUCER', 10);
define('PAGINATION_NEW_TYPE', 10);
define('PAGINATION_NEW', 20);
define('MESSAGE_NOT_FOUND_RECORD', 'Record not found');
define('MESSAGE_DELETE_ERROR', 'Delete error');
define('MESSAGE_DELETE_OK', 'Delete successful');
define('MESSAGE_CREATE_OK', 'Create successful');
define('MESSAGE_CREATE_ERROR', 'Create error');
define('MESSAGE_UPDATE_OK', 'Update successful');
define('MESSAGE_UPDATE_ERROR', 'Update error');
define('FORMAT_DATE', 'd/m/Y');
define('STR_LIMIT', 30);
define('STATUS_OK', 1);
define('STATUS_ERR', 0);
define('STATUS_FAILED', 2);
define('TYPE_STRING', 1);
define('TYPE_IMAGE', 2);
